CREATE TABLE city (
  uuid VARCHAR(60) PRIMARY KEY,
  cityName VARCHAR(60) UNIQUE NOT NULL,
  count INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);